services:
  go-server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      # Example environment variables
      ENV: "development"
      LOG_LEVEL: "info"
    volumes:
      - ./server:/app
  vue-client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: base
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app # Mount the local project directory
      - /app/node_modules # Ensure node_modules is local to the container
      - /app/.pnpm-store # Ensure node_modules is local to the container
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "dev"]
